### PR TITLE
Implement `Hash` for `Origin` (fix #302)

### LINKED ISSUE #302: Implement `Hash` for `Origin`
Seems like this could reasonable be used as a key, and `Hash` is a trait we implement eagerly.

### PR DESCRIPTION
**Pull request by cGuille**
Hello,

I'm a Rust / Open Source beginner, so just explain if anything is wrong. :-)

I am giving a try at issue #302. I just derived the `Hash` for the `Origin` type.

I have zero experience with testing in Rust so I just tried to demonstrate that it works, but I do not know how to write a good test for this.

What should I do now?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/321)

### CODE REVIEW

**Comment by skade** [comment]
@cGuille Wait for one of the maintainers to provide review :). Most maintainers of the URL crate live in the US, so this might take until later.

Ignore the nightly error in the linked travis test suite, rust nightly is currently broken, not this lib.

**Comment by emilio** [comment]
@SimonSapin is french fwiw, hopefully he can take a look soon-ish.

Can you test also that opaque origins get different hashes? (It's trivial, but worth having that in the test-suite too).

**Comment by cGuille** [comment]
Hello,

There is actually no hurry at all. :-)

I am OK with adding more tests ; I will just have to figure out how.
I do not like using `HashMap` to indirectly test the `Hash` trait ; it  would be nice to have someone else's opinion about this.

**Comment by SimonSapin** [comment]
@skade, unfortunately, most of the maintainers of the url crate are me :) I’m usually in UTC+1~2.

@cGuille You can hash without a hashmap like so:

```rust
use std::collections::hash_map::DefaultHasher;
use std::hash::Hash;

fn hash<T: Hash>(value: T) -> u64 {
    let mut hasher = DefaultHasher::new();
    value.hash(&mut hasher);
    hasher.finish()
}
```

To make the test more interesting, you could use different URLs that have the same origin. Please also test that hashing is consistent with `==` equality.

Thanks!

**Comment by cGuille** [comment]
Thank you!

I updated the PR to test hash values directly instead of using `HashMap`, but I do not know how to test that hashing is consistent with equality. Do you have something in mind?
Should I just check that equalities of the origins in my test are the same as the equalities of their hashes?

**Comment by SimonSapin** [comment]
Test that things that compare equal with `==` have the same hash. Test that things that compare unequal have a different hash. The latter is not guaranteed because there could be hashing collisions, but it is unlikely enough that it’s alright to test in a couple fixed-input test cases.

**Comment by cGuille** [comment]
What do you think about this? Are there enough URL samples?

**Comment by cGuille** [comment]
I solved the conflict with `master` and rebased the branch upon it.

Tell me if there is anything left to do regarding this PR.

**Comment by cGuille** [comment]
I rebased upon master to solve this second conflict.

Can this be merged?

**Comment by brson** [comment]
@bors-servo r+

bors-servo probably doesn't listen to me...

**Comment by brson** [comment]
Sorry for the delay @cGuille !

**Pull request merged**
