### PR TITLE
Bring fuzzer up to date

### PR DESCRIPTION
**Pull request by Hoverbear**
Went to go run some fuzzing today and hit some speed bumps. This brings it up to date and inline with the latest versions.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/342)

### CODE REVIEW

**Comment by Manishearth** [comment]
Could you also update the fuzz script to use the new macro format?

**Comment by Hoverbear** [comment]
One of these? https://github.com/rust-fuzz/cargo-fuzz/search?utf8=%E2%9C%93&q=macro_rules&type= I can't find any other associated macros.

**Comment by Manishearth** [comment]
Try creating a new script (`cargo fuzz add foo.rs`) and copy its contents.

**Comment by Hoverbear** [comment]
@Manishearth Thanks for the pointer. :) Updated.

**Pull request merged**
