### PR TITLE
Implement CheckHyphens

### PR DESCRIPTION
**Pull request by nox**
Fixes https://github.com/servo/rust-url/issues/483

This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/484)

### CODE REVIEW

**Comment by nox** [comment]
I need to write a test but lunch time is approaching. :)

**Comment by nox** [comment]
I made `idna::domain_to_ascii` not check hyphens, and `idna::uts46::to_ascii` continue to check hyphens by default. Not sure that this is the right trade-off to make.

**Comment by SimonSapin** [comment]
UTS 46 does not specify defaults for its flags, but checking hyphens is what previous versions did:

* https://www.unicode.org/reports/tr46/tr46-19.html#Validity_Criteria
* https://www.unicode.org/reports/tr46/tr46-17.html#Validity_Criteria

The URL standard explicitly sets `CheckHyphens` to false. So yes, I think these are the right defaults.

I think I’d rather not add a new `Config` type in the pubic API as long as `Flags` also exist. What do you think of keeping it private for now? I’ve filed https://github.com/servo/rust-url/issues/486 about cleaning this up on the next breaking change batch, and referenced it from https://github.com/servo/rust-url/issues/463.

**Comment by nox** [comment]
I don't think making `Config` public is an issue, even when `Flags` goes away in a future version `Config` will still be here. I tried to make the change anyway, and I can't use  `pub(crate)` because that stabilised in 1.18.0.

**Pull request merged**
