### PR TITLE
Prevent panic when calling `url::Url::set_host` with `None`.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/servo/rust-url/issues/243.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/244)

### CODE REVIEW

**Comment by valenting** [comment]
Note this line from the [URL spec](https://url.spec.whatwg.org/#hostname-state):
> If url is special and buffer is the empty string, return failure. 

So both set_host(None) and set_host("") should probably fail if SchemeType::from(self.scheme()).is_special()

So while the test should not crash, the result should not be https:/hello
The same test would be correct though, if the protocol were not special.

**Comment by frewsxcv** [comment]
@SimonSapin Do you remember why there is logic here for the 'cannot-be-a-base-URL' flag? At least for the link that @valenting sent, it doesn't look like that logic needs to be here.

**Pull request merged**
