### PR TITLE
Add examples Url methods

### PR DESCRIPTION
**Pull request by hngnaig**
Fix issue #309

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/326)

### CODE REVIEW

**Comment by SimonSapin** [comment]
This includes a lot of unrelated changes in the same commit, making it difficult to find out what actually changed.

For example, using `/*! … */` instead of `//!` for the crate’s doc-comment is deliberate: it make editing this very long comment much easier. Using two spaces before same-line comments is also a deliberate choice. Whitespace was added and removed at random places for no apparent reason.

**Comment by lucab** [comment]
@SimonSapin from a quick glance at this, the large diff seems to be due to a rustfmt pass. Perhaps you may want to do a repo-wide pass separately so that further PR can start from a clean base?

**Comment by dtolnay** [comment]
@hngnaig are you still working on rolling back those unrelated formatting changes?

**Comment by hngnaig** [comment]
@dtolnay sr for late, i still working on it, and commit rolling back those. :)

**Comment by hngnaig** [comment]
I open other [PR](https://github.com/servo/rust-url/pull/340) to remove rustfmt

**Pull request closed without merging**
