### PR TITLE
Fix no_std Support for idna

### PR DESCRIPTION
**Pull request by domenukk**
This fixes `no_std` builds for the `idna` crate.

### CODE REVIEW

**Comment by domenukk** [comment]
The CI error doesn't seem related to this PR:
`error: package `log v0.4.19` cannot be built because it requires rustc 1.60.0 or newer, while the currently active rustc version is 1.56.0
`

**Review by lucacasonato — COMMENTED** [review]
It's concerning we didn't catch this in CI. We should perform `no_std` builds for all crates in CI to catch stuff like this.

**Comment by domenukk** [comment]
There's a CI check in place in PR #831

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks

**Pull request merged**
