### PR TITLE
Fix #124 integer underflow in slicing base URL path components.

### LINKED ISSUE #124: Integer Overflow on odd `file` URL
This code:

```rust
"file:...".parse::<Url>();
```

will yield this error:

```
test tests::bad_file_url ... FAILED

failures:

---- tests::bad_file_url stdout ----
        thread 'tests::bad_file_url' panicked at 'arithmetic operation overflowed', src/parser.rs:287



failures:
    tests::bad_file_url

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

### PR DESCRIPTION
**Pull request by SimonSapin**
#124

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-url/125)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-url/125)

**Comment by metajack** [comment]
I guess this one isn't on bors yet. Fixing.

**Comment by SimonSapin** [comment]
I suspect Cargo will want this on crates.io. @alexcrichton ?

**Comment by alexcrichton** [comment]
That would indeed be nice :)

**Comment by SimonSapin** [comment]
@bors-servo retry

Timeout when downloading rust

**Pull request merged**
