### PR TITLE
Systematically ignore tabs and newlines, per spec change

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/whatwg/url/commit/7b40216f809c7fe3c9a1680b5c1b06a771c9ebd8
https://github.com/whatwg/url/issues/101

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/190)

### CODE REVIEW

**Comment by asajeffrey** [comment]
This seems like a lot of extra complexity to handle an uncommon case (URLs with tabs or spaces). It seems like there should be a simpler way to do this, something like making `Input` implement a peekable and perhaps cloneable iterator interface.

Am I right that one of the goals is to keep this as a one-pass algorithm, which is why the obvious brute force scan of the input for tabs and spacing before parsing (and filtering/collecting it if any are found) isn't acceptable?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/lib.rs, line 594 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFZebG_Clq9bt9At_N:-KGFZebG_Clq9bt9At_O:1648425534) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/lib.rs#L594)):*
It's a pity this (and the other functions like it) isn't just `input.chars().filter(is_url_char)`, possibly with some stuff about stripping off leading/trailing characters.

---

*[src/parser.rs, line 130 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFYl_6apPkRg9zQmgW:-KGFYl_7kOUYxbw7Qq02:260673116) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L130)):*
I'm a bit surprised we need this many helper methods. Does the URL parser need that many methods that aren't in some mix of `Peekable<Iterator<char>>`? and `IntoIterator`?

---

*[src/parser.rs, line 326 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGF_k44bcWIPK5NLwDz:-KGF_k44bcWIPK5NLwE-:753395594) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L326)):*
Why this change?

---

*[src/parser.rs, line 340 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGF_urHfThkDpKdr_Oq:-KGF_urHfThkDpKdr_Or:-1226380940) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L340)):*
This is doing a lot more allocation than the original.

---

*[src/parser.rs, line 351 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFaplXe_sEn3YmQ13a:-KGFaplXe_sEn3YmQ13b:-1737965309) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L351)):*
The code seems more complex now, is there a way to keep the simplicity of the original?

---

*[src/parser.rs, line 621 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFbdBqHOzqb1kYp0XF:-KGFbdBqHOzqb1kYp0XG:679217704) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L621)):*
More allocation.

---

*[src/parser.rs, line 678 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFbh--yA8FbevsRYtd:-KGFbh--yA8FbevsRYte:1293755090) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L678)):*
The new code is more complex.

---

*[src/parser.rs, line 745 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFc7rQuyj3qfVBs2Xz:-KGFc7rRjQJN6_JgyTuC:-1765442189) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L745)):*
And more complexity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/190#-:-KGFcLZuhqTmk0lu58tT:-18813303)*

**Comment by SimonSapin** [comment]
The complexity was already there, just (inconsistently) spread in various parts of the parser that used to each have code to ignore these characters. But with this spec change I think it would be unreasonable complex to ignore them manually *everywhere*, for example between the slashes of `http://`.

> something like making Input implement a peekable and perhaps cloneable iterator interface.

That’s kinda what this PR is all about? (`iterator.clone().next()` is the same as `peek` when `clone` is cheap.)

> Am I right that one of the goals is to keep this as a one-pass algorithm,

Yes. Or maybe filtering and collecting into a `String` is acceptable, but it seemed undesirable. I don’t know.

---

Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/lib.rs, line 594 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFZebG_Clq9bt9At_N:-KGG1I10vKsDcJLcMZWx:132224259) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/lib.rs#L594)):*
That’s… exactly what `Input` is?

---

*[src/parser.rs, line 130 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFYl_6apPkRg9zQmgW:-KGG1T_tHyfdvXcpyJ9P:-112688087) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L130)):*
Sure, you can always manually inline all these helpers instead of having them in methods. But that’s overall more code, mostly duplicated?

---

*[src/parser.rs, line 326 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGF_k44bcWIPK5NLwDz:-KGG1l9kKmTFxEaASqwC:-807446871) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L326)):*
`str::find` returns a byte index that can be used for indexing. `Input` supports neither indexing nor `.len()`.

---

*[src/parser.rs, line 340 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGF_urHfThkDpKdr_Oq:-KGG1zp3p5esLfKPxXYa:-1998187133) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L340)):*
Only for users that want the full details of "syntax violations", which so far no-one has ever used as far as I know.

---

*[src/parser.rs, line 351 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFaplXe_sEn3YmQ13a:-KGG2xmipcg0Z1x4Qzch:-589062986) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L351)):*
If this comment is about this specific line, I don’t see how it is more complex. If it is about this PR in general… do you have a more concrete suggestion?

---

*[src/parser.rs, line 621 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFbdBqHOzqb1kYp0XF:-KGG396GpeuAA7fmVAl1:508649317) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L621)):*
Still only when logging "syntax violations".

---

*[src/parser.rs, line 678 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFbh--yA8FbevsRYtd:-KGG3J8yyDC44K5qKqCB:1443224884) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L678)):*
¯\_(ツ)_/¯

This PR is not just an internal refactoring. It’s about implementing a change (linked from the PR message) in the specification’s requirements.

If you look at individual commits, the first one "Parse based on iterators" *is* a refactoring that doesn’t change the behavior, but it only exists to enable the behavior change in the second commit "Systematically ignore tabs and newlines".

---

*[src/parser.rs, line 745 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGFc7rQuyj3qfVBs2Xz:-KGG3v2FWSIh8tL8Y45O:1825643046) ([raw file](https://github.com/servo/rust-url/blob/e55d437ffcadf1774a6bdc137b20564e9c64cbeb/src/parser.rs#L745)):*
See previous comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/190#-:-KGG0Qg_hjDADDyzERbZ:751562113)*

**Comment by asajeffrey** [comment]
Archiving an IRC conversation: http://logs.glob.uno/?c=mozilla%23servo&s=26+Apr+2016&e=26+Apr+2016#c415136

**Comment by asajeffrey** [comment]
I think at this point we're into style differences. You can r=me. Squash the commits?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/parser.rs, line 107 \[r2\]](https://reviewable.io:443/reviews/servo/rust-url/190#-KGIlccck3Yi1HSlx8Nz:-KGIlccdTLcpAfTgGiwz:264720186) ([raw file](https://github.com/servo/rust-url/blob/cd7d83b631076cc23228764c4a1bdb8a3f6f5d43/src/parser.rs#L107)):*
Much nicer!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/190#-:-KGImCuGXSnqo0mE6nbO:-767757967)*

**Comment by SimonSapin** [comment]
Commits are as intended.

@bors-servo r+

**Pull request merged**
