### PR TITLE
Implement Serialize and Deserialze for Host

### PR DESCRIPTION
**Pull request by cbrewster**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/272)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good! Just some minor details.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Cargo.toml, line 4 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBH_JdorypgnrIY9I7:-KbBH_JdorypgnrIY9I8:bjbflf4) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/Cargo.toml#L4)):*
> ```TOML
> 
> name = "url"
> version = "1.3.1"
> ```

This PR introduces new functionality, so I think SemVer says the version number should be 1.4.0.

---

*[src/host.rs, line 61 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBHisrfaPKLmcVa0on:-KbBHisrfaPKLmcVa0oo:b62qtq0) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L61)):*
> ```Rust
> 
> #[cfg(feature="serde")]
> impl ::serde::Serialize for Host {
> ```

`Host<S=String>` is generic (with a default). I think this impl should be `impl<S: AsRef<str>> ::serde::Serialize for Host<S>`. For example `Host<&str>` is used in `Url::host`.

---

*[src/host.rs, line 73 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBIUsZ7m1nWDv7dlc-:-KbBIUs_odsya_8t6gJd:b-ded397) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L73)):*
> ```Rust
> 
> #[cfg(feature="serde")]
> impl::serde::Deserialize for Host {
> ```

This is probably less important than for `Serialize` (since `Self` is used in an owned return value, and so can not contains `&str`), but while you’re at it please make this impl generic as well: `impl<S: From<String>> ::serde::Deserialize for Host<S>`.

---

*[src/host.rs, line 73 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBJ4YaGwZbym-hEGQS:-KbBJ4YaGwZbym-hEGQT:bvdy8n0) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L73)):*
> ```Rust
> 
> #[cfg(feature="serde")]
> impl::serde::Deserialize for Host {
> ```

Nit: space before `::serde`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/272#-:-KbBJFdDA9jXpWlTDj3r:bpose0s)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Cargo.toml, line 4 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBH_JdorypgnrIY9I7:-KbBPr1S4UkbIJK9kT0Y:b-4idid8) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/Cargo.toml#L4)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

This PR introduces new functionality, so I think SemVer says the version number should be 1.4.0.
</blockquote></details>

I think RFC 1105 allows this as a minor change: https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-adding-new-public-items.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/272)*

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Cargo.toml, line 4 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBH_JdorypgnrIY9I7:-KbBTuL3KqgiQ7Dw1c6d:b-4fbbgm) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/Cargo.toml#L4)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary><blockquote>

I think RFC 1105 allows this as a minor change: https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-adding-new-public-items.
</blockquote></details>

Yes, it’s not a breaking change. That would be version 2.0.0.

Cargo treats 1.3.1 and 1.4.0 the same, the difference is only for communicating to humans. (I’d be fine with just two components in the version number, but SemVer seems to be what the Rust ecosystem settled on.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/272)*

**Comment by cbrewster** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[Cargo.toml, line 4 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBH_JdorypgnrIY9I7:-KbG8qSMm9XZUF3iKUGE:b-896fix) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/Cargo.toml#L4)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Yes, it’s not a breaking change. That would be version 2.0.0.

Cargo treats 1.3.1 and 1.4.0 the same, the difference is only for communicating to humans. (I’d be fine with just two components in the version number, but SemVer seems to be what the Rust ecosystem settled on.)
</blockquote></details>

Done.

---

*[src/host.rs, line 61 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBHisrfaPKLmcVa0on:-KbG8sfE_Y_ncIEqcwrp:b2hmfhj) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L61)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

`Host<S=String>` is generic (with a default). I think this impl should be `impl<S: AsRef<str>> ::serde::Serialize for Host<S>`. For example `Host<&str>` is used in `Url::host`.
</blockquote></details>

Done. I had to also add a Serialize bound.

---

*[src/host.rs, line 73 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBIUsZ7m1nWDv7dlc-:-KbG8w0FuTaYw30Y_fOG:bc4fqug) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L73)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

This is probably less important than for `Serialize` (since `Self` is used in an owned return value, and so can not contains `&str`), but while you’re at it please make this impl generic as well: `impl<S: From<String>> ::serde::Deserialize for Host<S>`.
</blockquote></details>

Done. I had to also add a Deserialize bound.

---

*[src/host.rs, line 73 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBJ4YaGwZbym-hEGQS:-KbG8wzzFvRBeX6x7ZSC:b-896fix) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L73)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Nit: space before `::serde`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/272)*

**Comment by SimonSapin** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/host.rs, line 61 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBHisrfaPKLmcVa0on:-KbGEhhd3vsYfjzySJPN:b-6c1epv) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L61)):*
<details><summary><i>Previously, cbrewster (Connor Brewster) wrote…</i></summary><blockquote>

Done. I had to also add a Serialize bound.
</blockquote></details>

I was thinking of serializing the result of `as_ref()`. I hadn’t thought of using a `Serialize` bound. Since the latter is more generic let’s keep it. But now the `AsRef` bound is unnecessary, so please remove it.

---

*[src/host.rs, line 73 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBIUsZ7m1nWDv7dlc-:-KbGF6qASmbizNhhhCqw:b-cy22iy) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L73)):*
<details><summary><i>Previously, cbrewster (Connor Brewster) wrote…</i></summary><blockquote>

Done. I had to also add a Deserialize bound.
</blockquote></details>

Same as above, please remove the `From` bound as it is unnecessary with the `Deserialize` one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/272)*

**Comment by cbrewster** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/host.rs, line 61 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBHisrfaPKLmcVa0on:-KbGFepzRuDmLbSVloqd:b-896fix) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L61)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

I was thinking of serializing the result of `as_ref()`. I hadn’t thought of using a `Serialize` bound. Since the latter is more generic let’s keep it. But now the `AsRef` bound is unnecessary, so please remove it.
</blockquote></details>

Done.

---

*[src/host.rs, line 73 at r1](https://reviewable.io:443/reviews/servo/rust-url/272#-KbBIUsZ7m1nWDv7dlc-:-KbGFeBs3_LF5wkuyahU:b-896fix) ([raw file](https://github.com/servo/rust-url/blob/d7e7e24966da05ed5671c4bb587ebf315fb5b96b/src/host.rs#L73)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Same as above, please remove the `From` bound as it is unnecessary with the `Deserialize` one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/272)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/272#-:-KbGGUH3XlglGFNcfqSp:bkg9nno)*

**Pull request merged**
