### PR TITLE
Pin unicode-normalization for Rust 1.33 CI build

### PR DESCRIPTION
**Pull request by mbrubeck**
See #566 for details.

### CODE REVIEW

**Comment by o0Ignition0o** [comment]
In order to not have [MaybeUninit](https://github.com/servo/rust-smallvec/pull/180) I think we want to have precise flags on smallvec as well as on unicode-normalization

**Comment by mbrubeck** [comment]
Any smallvec 0.6 version is compatible with Rust 1.33, so pinning unicode-normalization to 0.1.9 should be sufficient.

I'm not sure why the failing Travis build is using unicode-normalization 0.1.11.  The script is working correctly locally...

**Comment by o0Ignition0o** [comment]
Oh that's weird indeed, I was pretty confident smallvec version = "0.6.13" carried a backport of maybeuninit.

Sorry for the noise

**Comment by mbrubeck** [comment]
smallvec 0.6.13 uses the `maybe-uninit` crate which is compatible with Rust 1.20 and later.

**Comment by o0Ignition0o** [comment]
Oh ok, thanks for pointing it out to me ! :)

**Comment by mbrubeck** [comment]
I think the previous error was caused by rust-lang/cargo#6904. Trying a workaround.

**Comment by o0Ignition0o** [comment]
And it passed ! 🎉

**Comment by mbrubeck** [comment]
> So if I get your force push correctly, cargo update actually caused a cargo.lock to be created, which works around the bug you refered to ?

Right.

**Comment by SimonSapin** [comment]
Thanks for the PR but this approach feels dissatisfying to me. I think I’d prefer either to have this requirement in `idna`’s `Cargo.toml`, or to stop testing on 1.33 and do 1.36 instead. I’m still not sure which is best, though.

**Pull request closed without merging**
