### PR TITLE
Don’t remove leading dots in domain names

### LINKED ISSUE #166: Panic when parsing a `.` in file URLs
Parsing the url `file://./foo` will cause rust-url to panic, for example:

``` rust
let _url = url::Url::parse("file://./foo");
```

yields:

```
thread '<main>' panicked at 'a non-empty list of numbers', ../src/libcore/option.rs:335
stack backtrace:
   1:     0x7fda97eb0f40 - sys::backtrace::tracing::imp::write::haa19c02b4de52f3bG0t
   2:     0x7fda97eb3075 - panicking::log_panic::_<closure>::closure.41218
   3:     0x7fda97eb2af0 - panicking::log_panic::h527fe484e9de8fe1W7x
   4:     0x7fda97ead303 - sys_common::unwind::begin_unwind_inner::h51f64b1a34c60827fTs
   5:     0x7fda97ead418 - sys_common::unwind::begin_unwind_fmt::h0845853a1913f45blSs
   6:     0x7fda97eb05a1 - rust_begin_unwind
   7:     0x7fda97ede0cf - panicking::panic_fmt::h3967afc085fe8067LFK
   8:     0x7fda97e8ffb5 - option::_<impl>::expect::expect::h6499254404020416113
                        at ../src/libcore/macros.rs:29
   9:     0x7fda97e8c02d - host::parse_ipv4addr::h8bc077b4a80e7f06FIa
                        at src/host.rs:186
  10:     0x7fda97e886b8 - host::_<impl>::parse::hd99c67cae0091fc0Uya
                        at src/host.rs:61
  11:     0x7fda97e98e65 - parser::parse_file_host::ha2c614830ab90204nKb
                        at src/parser.rs:469
  12:     0x7fda97e926b0 - parser::parse_relative_url::h4e24ca8208217f655mb
                        at src/parser.rs:217
  13:     0x7fda97e85497 - parser::parse_url::hdcd76e516d93c3d01eb
                        at src/parser.rs:122
  14:     0x7fda97e80a2b - _<impl>::parse::h6996f44ab86e41c8w1p
                        at src/lib.rs:437
  15:     0x7fda97e809eb - _<impl>::parse::h6fc311753b000c53hlq
                        at src/lib.rs:566
  16:     0x7fda97e80998 - main::h13ef09143d6a2ad6faa
                        at src/main.rs:4
  17:     0x7fda97eb2894 - sys_common::unwind::try::try_fn::h11901883998771707766
  18:     0x7fda97eb03e8 - __rust_try
  19:     0x7fda97eb2536 - rt::lang_start::hc150f651dd2af18b44x
  20:     0x7fda97e81be9 - main
  21:     0x7fda9722cec4 - __libc_start_main
  22:     0x7fda97e80878 - <unknown>
  23:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes #166, closes #170.

http://www.unicode.org/reports/tr46/#ToASCII has algorithms like:

> - Break the result [a domain] into labels at U+002E FULL STOP.
> - […]
> - join the labels using U+002E FULL STOP as a separator

Before this PR, the IDNA code does "join" with code like:

``` rust
     let mut result = String::new();
     for label in /* ... */ {
         if result.len() > 0 {
             result.push('.');
         }
         result.push_str(/* ... */)
     }
```

This writes a dot before every label, except the first. But this code seems to be buggy: if all labels so far are empty, it won’t push dots to separate empty labels. In other words, leading dots are stripped.

I’ve fixed this apparent bug by using a boolean, but a number of tests started failing. They apparently expect leading dots to be stripped. I don’t see any thing in the spec to support this behavior.

@valenting did you mean to strip leading dots in this code? Am I missing something in the spec?

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-url/171)

### CODE REVIEW

**Comment by valenting** [comment]
I don't recall if my implementation happened to match the unit tests, or if I changed the implementation to match the unit tests.
But I do agree that the spec doesn't specify this, and your patch makes more sense.
We should raise this issue with the unicode group, to get the unit tests fixed.

**Comment by valenting** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/servo/rust-url/171#-KBxxOwXdbMIO-8sTygL:-KBxxOwY8FnefgP6wCv9:-855967974) (no related file):*
Sorry I never completed this review. As I said, this makes sense, and I think we should land it.

---

*[tests/tests.rs, line 119 \[r1\]](https://reviewable.io:443/reviews/servo/rust-url/171#-KBxwuZEMx1D3KnVM96y:-KBxwuZEMx1D3KnVM96z:-18477990) ([raw file](https://github.com/servo/rust-url/blob/9d0fd21ab002e59479610166956b04e98c7d186f/tests/tests.rs#L119)):*
Interestingly, not how Firefox parses this URL :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-url/171)*

**Comment by Manishearth** [comment]
Just realized that this is the same as https://github.com/servo/rust-url/pull/256 .

Both chrome and firefox do not strip any dots, and the spec agrees with this. We should land either this or #256

We're not running the IDNA tests on CI, btw, so we already have a bunch that fail.

**Comment by Manishearth** [comment]
> But I do agree that the spec doesn't specify this

The spec says to "join using full stops", and the "join" operation usually means putting the given delimeter between the segments, even if they are empty. `["","",""].join('.') == ".."`

**Comment by SimonSapin** [comment]
What bothers me about this change, and why this PR isn’t merged yet, is that it makes some IDNA tests fail. It looks like these tests might be wrong? But the Unicode Technical Committee has been completely unresponsive to reports of spec issues so far, so I don’t know what to do here.

**Comment by Manishearth** [comment]
The tests are wrong -- they don't agree with the spec nor the implementations.

**Comment by Manishearth** [comment]
Anyway, r=me on this change

**Comment by dtolnay** [comment]
This is still waiting for a response from the Unicode Technical Committee right?

**Comment by behnam** [comment]
I have submitted a new PR, based on this, which also has a fix for the conformance tests: https://github.com/servo/rust-url/pull/337

About the spec and test data issues, please see discussion on the issue: https://github.com/servo/rust-url/issues/166

With those, I recommend closing this old PR.

**Comment by Hoverbear** [comment]
Closing this as requested.

**Pull request closed without merging**
