### PR TITLE
upstream rust: std::path moved to std::old_path

### PR DESCRIPTION
**Pull request by mikedilger**
Just changed all references to std::path to std::old_path to keep it compiling.
Further work will be needed to use the new std::path

### CODE REVIEW

**Comment by Hoverbear** [comment]
Hi! Thanks for your contribution!

**Comment by Hoverbear** [comment]
@SimonSapin It looks like `0.2.19` was pushed without the `Cargo.toml` being updated. I'm pushing this as `0.2.20`

**Comment by SimonSapin** [comment]
Oops, I published 0.2.19 that fixed the same thing but forgot to push it. Sorry! Should be pushed/merged now.

**Comment by Hoverbear** [comment]
@SimonSapin Oh, alright! I thought I messed something up.

**Pull request merged**
