### PR TITLE
Add a few doc examples.

### PR DESCRIPTION
**Pull request by frewsxcv**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/228)

### CODE REVIEW

**Comment by untitaker** [comment]
Spurious CI failure.

**Comment by Hoverbear** [comment]
Restarting build.

**Comment by Hoverbear** [comment]
Tests pass! =D

**Comment by SimonSapin** [comment]
Sorry I forgot about this.

@bors-servo r+

**Pull request merged**
