### PR TITLE
[idna] Update data to Unicode 10.0 and fix logic

### PR DESCRIPTION
**Pull request by behnam**
* Change the behavior of ToASCII step to match the spec and prevent failures on some cases when a domain name starts with leading dots (FULL STOPs), as requested in #166. (Another attempt on https://github.com/servo/rust-url/pull/337 and https://github.com/servo/rust-url/pull/171)

* Update `IdnaTest.txt` file to UCD 10.0 and fix Validation Rules, specially Bidi Rules, for the tests to pass.

* Add TODO marks for new flags introduced in Unicode 10.0 version of UTS#46. (http://www.unicode.org/reports/tr46/proposed.html)

* Add integration test for `rust-url` crate for the new behavior.

Fix https://github.com/servo/rust-url/issues/166

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/351)

### CODE REVIEW

**Comment by behnam** [comment]
Filed https://github.com/unicode-rs/unicode-normalization/issues/16 for `is_combining_mark()` failure for `U+11C3A`.

**Comment by behnam** [comment]
Now that `unicode-normalization` is fixed, I dropped the workaround the workaround in latest update: https://github.com/behnam/rust-url/tree/ucd10

**Comment by SimonSapin** [comment]
Sorry for the delays and repeated conflicts. If you’d prefer I can take over and do the minor changes I requested below.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Cargo.toml, line 5 at r5](https://reviewable.io:443/reviews/servo/rust-url/351#-Kn4jxh15DKMzxDi5Yxx:-Kn4jxh15DKMzxDi5Yxy:bm9xbyt) ([raw file](https://github.com/servo/rust-url/blob/d0eb5bfe99edcd780670b77f759da966c7535545/Cargo.toml#L5)):*
> ```TOML
> name = "url"
> # When updating version, also modify html_root_url in the lib.rs
> version = "1.5.1"
> ```

This change is not necessary, please remove it. Since the new version of idna is semver-compatible, end-users can update to it independently of url.

---

*[Cargo.toml, line 45 at r5](https://reviewable.io:443/reviews/servo/rust-url/351#-Kn4kEVXMlR7oCxKg9Nv:-Kn4kEVXMlR7oCxKg9Nw:b-fx8fts) ([raw file](https://github.com/servo/rust-url/blob/d794e04b12a2127e67ce523a4d867967d348f8ca/Cargo.toml#L45)):*
> ```TOML
> encoding = {version = "0.2", optional = true}
> heapsize = {version = ">=0.1.1, <0.5", optional = true}
> idna = { version = "0.1.0", path = "./idna" }
> ```

This is also unnecessary. "0.1.0" means ">=0.1.0,<0.2.0", same as "0.1".

---

*[idna/src/uts46.rs, line 416 at r4](https://reviewable.io:443/reviews/servo/rust-url/351#-Kn4iIj-OyLluFOJV1_O:-Kn4iIj0D_UrqMKqqGeb:bqk7g1h) ([raw file](https://github.com/servo/rust-url/blob/ea29c3d2f26afa8a7d49ecb593975fa1a0dff4c0/idna/src/uts46.rs#L416)):*
> ```Rust
> 
> #[cfg(test)]
> mod tests {
> ```

`Cargo.toml` specifies `[lib] test = false` to avoid compiling the library code twice, so these tests are never run. Please move them to a new `idna/tests/unit.rs` file and add a `[[test]] name = "unit"` section in `Cargo.toml`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/351#-:-Kn4kXOuIc7hqcbGiWse:bpw662o)*

**Comment by behnam** [comment]
Thanks for the review, @SimonSapin. I've addressed all the comments and rebased, so should be good to land.

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[idna/src/uts46.rs, line 416 at r4](https://reviewable.io:443/reviews/servo/rust-url/351#-Kn4iIj-OyLluFOJV1_O:-Kn5XOUhYFRNlkHInKjN:b-896fix) ([raw file](https://github.com/servo/rust-url/blob/ea29c3d2f26afa8a7d49ecb593975fa1a0dff4c0/idna/src/uts46.rs#L416)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

`Cargo.toml` specifies `[lib] test = false` to avoid compiling the library code twice, so these tests are never run. Please move them to a new `idna/tests/unit.rs` file and add a `[[test]] name = "unit"` section in `Cargo.toml`.
</blockquote></details>

Done.

---

*[Cargo.toml, line 5 at r5](https://reviewable.io:443/reviews/servo/rust-url/351#-Kn4jxh15DKMzxDi5Yxx:-Kn5XQQ1skShCALK4lbH:b-896fix) ([raw file](https://github.com/servo/rust-url/blob/d0eb5bfe99edcd780670b77f759da966c7535545/Cargo.toml#L5)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

This change is not necessary, please remove it. Since the new version of idna is semver-compatible, end-users can update to it independently of url.
</blockquote></details>

Done.

---

*[Cargo.toml, line 45 at r5](https://reviewable.io:443/reviews/servo/rust-url/351#-Kn4kEVXMlR7oCxKg9Nv:-Kn5XRAkxjA5I_lSjjvl:b-896fix) ([raw file](https://github.com/servo/rust-url/blob/d794e04b12a2127e67ce523a4d867967d348f8ca/Cargo.toml#L45)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

This is also unnecessary. "0.1.0" means ">=0.1.0,<0.2.0", same as "0.1".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/351#-:-Kn5XSI4ppowA52W4Dva:bhcgcnv)*

**Comment by SimonSapin** [comment]
Reviewed 1 of 2 files at r7, 2 of 3 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[idna/src/uts46.rs, line 346 at r10](https://reviewable.io:443/reviews/servo/rust-url/351#-Kn8UharzVwEy_PCEilo:-Kn8UharzVwEy_PCEilp:b-ka4k9t) ([raw file](https://github.com/servo/rust-url/blob/f60d7011514fd8901271cece50e7744b0b95865d/idna/src/uts46.rs#L346)):*
> ```Rust
> 
> #[derive(PartialEq, Eq, Clone, Copy, Debug)]
> pub enum Error {
> ```

Can we not make this public? That would mean that adding a new variant (like you did in another commit of this PR) would be a breaking change. It looks like unit tests don’t need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/351)*

**Comment by behnam** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[idna/src/uts46.rs, line 346 at r10](https://reviewable.io:443/reviews/servo/rust-url/351#-Kn8UharzVwEy_PCEilo:-Kn8vv5yeM8YTTcGQ4wt:b4ti7tw) ([raw file](https://github.com/servo/rust-url/blob/f60d7011514fd8901271cece50e7744b0b95865d/idna/src/uts46.rs#L346)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Can we not make this public? That would mean that adding a new variant (like you did in another commit of this PR) would be a breaking change. It looks like unit tests don’t need it.
</blockquote></details>

Right, there was no need for it anymore. Reverted it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/351)*

**Comment by behnam** [comment]
Also updated the `IdnaTest` file to final release, which came out yesterday. So, there's nothing left from the *draft* versions and we're all up to date.

**Comment by behnam** [comment]
Btw, updating `uts46_mapping_table.rs` to Unicode 10.0.0 should be done in a separate diff. Let me know if you like me to submit a PR.

**Comment by SimonSapin** [comment]
Looks great, thanks!

@bors-servo r+

> Btw, updating uts46_mapping_table.rs to Unicode 10.0.0 should be done in a separate diff. Let me know if you like me to submit a PR.

Please do. (I’m a bit surprise the new tests pass without the new data. Maybe the tests don’t cover the normative differences.)

---

Reviewed 1 of 4 files at r6, 1 of 2 files at r12, 1 of 1 files at r13, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/351#-:-Kn9QF-4et0yJPjR3gdM:b-6updxq)*

**Pull request merged**
