### PR TITLE
Introduce Url::join

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-url/153)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r=me with a version number bump

**Comment by SimonSapin** [comment]
Sorry, I should have been more precise. This should be 0.5.2, not 0.6.0 since it’s a backward compatible addition. (And updating all the things for semver-incompatible versions is a pain.)

**Comment by nox** [comment]
@SimonSapin Sorry myself, I know the rules, just forgot that semver with 0.y.z is different than with 1.y.z.

**Pull request merged**
