### PR TITLE
Add HeapSizeOf impl for ParseError

### PR DESCRIPTION
**Pull request by KiChjang**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/370)

### CODE REVIEW

**Comment by SimonSapin** [comment]
* Please use the `known_heap_size!` macro when possible
* This does not compile. You need `#[…]` syntax to add an attribute to the next item, rather than `#![…]` which adds an attribute to the thing that contains such syntax.

**Comment by KiChjang** [comment]
Ack, that was embarrassing. Fixed.

**Comment by SimonSapin** [comment]
Thanks!

@bors-servo r+

**Comment by KiChjang** [comment]
Published this as 1.5.1.

**Pull request merged**
