### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/517)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@nox r? for my commits

**Comment by nox** [comment]
r+ your commits, let's merge it on 2.0 so we can continue making changes there.

**Comment by SimonSapin** [comment]
This is the `2.0` branch.

**Comment by nox** [comment]
Yeah I know, I meant we should merge it so we can make other PRs against 2.0, sorry that wasn't clear.

**Comment by SimonSapin** [comment]
Per IRC discussion:

@bors-servo r=nox

**Pull request merged**
