### PR TITLE
use checked addition to not panic in debug build

### PR DESCRIPTION
**Pull request by Skgland**
used checked addition so this does not panic in debug builds

related to issue #870 

~~not sure if #870 is completely resolved as there are other comments indicating a possible overflow condition that I did not understand and as such did not fix~~

### CODE REVIEW

**Comment by Skgland** [comment]
Its also probably not ideal tha the fixed code and the test are in different crates, but I didn't know how to separate the punycode from the url and how to add a test in the punycode crate as that appears to use a custom testing framework

**Comment by Skgland** [comment]
> not sure if #870 is completely resolved as there are other comments indicating a possible overflow condition that I did not understand and as such did not fix

I think the line I was refering to is fine: 
`min_code_point - code_point > (u32::MAX - delta) / (processed + 1)`

`min_code_point` should be lager than `code_point` due to the iterator filter `c >= code_point` as such this can't underflow

`u32::MAX - delta` cannot underflow either as `delta` can't be larger than `u32:MAX`

`process + 1` can't overflow as `process < input_length` per the while condition

`process + 1` is not 0 as process is unsigned, so no division by zero

**Comment by Skgland** [comment]
Restructured changes and moved test to idna where it belongs in my opinion.
- The first commit fixes the line endings of `debug_metadata/README.md` as it was always considered dirty and prevented me from rebasing otherwise.
- The second commit adds the test, fails without the third commit.
- The third and last commit fixed the panic in debug builds due to overflow.

**Comment by Skgland** [comment]
Rebase again as I accidentally hardcoded the string in the Bad Punycode test instead of using the value(s) from `bad_punycode_tests.json`.

**Comment by Skgland** [comment]
This should now be ready for review again.

**Comment by Skgland** [comment]
Fixed added test to not increase msrv beyond 1.56 and fixed clippy lint.
Ready for review again.

**Comment by Skgland** [comment]
Now with fixed formatting.
Ready for review again, sorry for the noise.

**Comment by Skgland** [comment]
I messed up my rebase, one moment.

**Comment by Skgland** [comment]
Ok, now the rebase should be fixed.

**Review by valenting — APPROVED** [review]
Thank you for the fix. I really appreciate it.

**Pull request merged**
