### PR TITLE
Add support for Serde 1.0

### LINKED ISSUE #304: Move serde 1.0 support in-crate
Today serde 1.0 is supported in its own `url_serde` crate, so that url can support both old serde and new serde. @dtolnay has some plan to hack support for both in-crate, though presumably serde_url will need to continue on until a major bump.

### LINKED ISSUE #320: Figure out a way to support multiple versions of serde in-crate
This is a requirement for doing #304 without a breaking change.

@dtolnay suggested a plan along these lines:

* Make a `serde_1_0` crate that depends on serde 1.0 and only contains `pub use serde::*;`. Make other similar crates for other mutually-incompatible versions of serde.  (I’d rather the serde project maintain these crates, if they’re willing.)
* Have `url` optionally depend on these crates, with Cargo feature flags named `serde_1_0` etc.
* Implement multiple versions of the `Serialize` and `Deserialize` traits. For example `impl serde_1_0::Serialize for Url {…} impl serde_0_9::Serialize for Url {…}` etc.
* Publish a new, compatible version of `url_serde` that is marked `#[deprecated]` with a message that point to the feature flags.

Open question: can `#[derive]` be used in this setup? How?

These crates with a version number in the name are a hack to work around a limitation of Cargo: a crate can not depend on multiple crates with the same name. (That is, multiple mutually-incompatible versions of the same crate.) A better solution would be to make Cargo support that scenario directly. This probably involves locally renaming a dependency for disambiguating `extern crate`.

Help wanted to write a Cargo RFC.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #304, fixes #320.

r? @SimonSapin

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/327)

### CODE REVIEW

**Comment by SamWhited** [comment]
LGTM; thanks for the comments on the copy/pasted code that could be custom derived, saved me trying to figure out why derive wasn't used.

**Comment by dtolnay** [comment]
I fixed the conflict with #331.

**Comment by drusellers** [comment]
Looking forward to serde 1.0 support landing

**Comment by SimonSapin** [comment]
I find the code in `src/serde.rs`, especially `Deserilize` impls for enum, to be overly verbose. It sounds like `extern crate serde;` in the code generated by `derive` is the only reason we can’t use `derive` instead. I’ve filed https://github.com/serde-rs/serde/issues/953 to request a serde feature that hopefully will fix that. I’d much prefer to use derive here.

**Comment by SimonSapin** [comment]
@drusellers In the meantime, https://docs.rs/url_serde/0.2.0/url_serde/ supports serde 1.0 today.

**Comment by konstin** [comment]
Unfortunately, url_serde doesn't work on existing types, e.g. `Vec<Url>`, so using serde in my project is currently blocked by this PR.

**Comment by Object905** [comment]
@konstin you can use `Vec<url_serde::SerdeUrl>` instead.

**Comment by killercup** [comment]
I really wanted to do a cool demo in a talk where I fetch <http://readrust.net/rust2018/feed.json>, first show a nice list of posts, and as a bonus quickly extract the domain to see ho many people are using gist.github.com as their blog. Not having serde 1.0 support basically destroys that bonus feature :(

**Comment by SimonSapin** [comment]
@killercup See https://github.com/servo/rust-url/pull/327#issuecomment-308139040 above.

**Comment by killercup** [comment]
@SimonSapin that's why I wrote "I really wanted to do a *cool* demo" 😉 

Adding two crates and using

```rust
#[serde(with = "url_serde")]
url: Url,
```

is not nearly as cool as just writing `url: Url,`.

**Comment by SimonSapin** [comment]
Sorry that SemVer spaghetti is not cool :) I’m considering doing url 2.0 at some point to fix this and other things, but for Servo to use be able to update it’d first need to update hyper from 0.10 to 0.11, which seems to be blocked on websocket support: https://github.com/servo/servo/issues/18518.

But since I’d rather not maintain two branches of url and I seem to be the one doing all that work anyway, url 2.0 will wait.

**Comment by killercup** [comment]
Ah, I see. That's indeed a pretty big chunk of spaghetti you have on your plate!

I kinda thought using the serde09 crate would resolve this, but I guess the issues run quite a lot deeper than that.

**Comment by dtolnay** [comment]
@SimonSapin I rebased and removed the 1.0 impls for Host\<S\> and HostInternal, because I believe most users are really only looking for Serde impls for url::Url. That one does not require serde_derive because we are serializing the url in string form.

**Comment by LegNeato** [comment]
Any update on this? Is this landable? Did something similar land?

**Comment by est31** [comment]
The 2.0 branch [has been opened](https://github.com/servo/rust-url/issues/463#issuecomment-510963476). Per [prior statements](https://github.com/servo/rust-url/issues/304#issuecomment-430619148), this PR should be closed and instead a PR against that branch filed.

I have made an alternative serde 1.0 implementation that's closer to the current implementation: https://github.com/servo/rust-url/compare/2.0...est31:serde_1.0

I think that this PR's serialization should be used instead where url's are just serialized as strings.

**Comment by SimonSapin** [comment]
Thanks for the PR, David. The version looks more reasonable than the original.

I’m going to close this since I took https://github.com/servo/rust-url/pull/512 instead, to be part of url 2.0.0. Hopefully it’ll be easy enough for the ecosystem to migrate, but if not we can consider reviving this PR in the `1.x` branch.

**Pull request closed without merging**
