### PR TITLE
[WIP] Modify examples to not call `unwrap`

### PR DESCRIPTION
**Pull request by luisbg**
This is for issue #312 

Just fixing one case to check this is what the issue is about and that I understand the intended fix.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/345)

### CODE REVIEW

**Comment by behnam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/lib.rs, line 270 at r1](https://reviewable.io:443/reviews/servo/rust-url/345#-Kkmf020Z-5VUBuS55Qk:-Kkmf020Z-5VUBuS55Ql:bv9z4k2) ([raw file](https://github.com/servo/rust-url/blob/752423ae35672ffeea31e464273a0c2cacecf1d3/src/lib.rs#L270)):*
> ```Rust
>     /// use url::Url;
>     ///
>     /// fn foo() -> Result<(), url::ParseError> {
> ```

If you like to keep the function definition part of the example, then the content of the block should be indented.

But, rustdoc has a nice way of letting you hide these *execution* details, using `# ` at the beginning of a line.

For example, this part would be:
```
    /// # fn foo() -> Result<(), url::ParseError> {
    /// ...
    /// # Ok(())
    /// # }
```

More here: https://doc.rust-lang.org/book/documentation.html#documenting-macros

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/345)*

**Comment by behnam** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-url/345)*

**Comment by luisbg** [comment]
Cool!

I will fix this tomorrow, probably. Currently traveling for work meeting so might not have the time to get around to it.

**Comment by mgeisler** [comment]
I believe you should also include a call to the `foo()` function -- otherwise the code in question is only compiled, but not actually executed.

**Comment by luisbg** [comment]
I am looking at this again. Will report soon. Sorry for the delay.

**Comment by Enet4** [comment]
#312 has been addressed in #323 (see the latest [Url#join](https://github.com/servo/rust-url/blob/master/src/lib.rs#L292-L305) for instance). Are there any new examples with `unwrap` since then?

**Comment by SimonSapin** [comment]
This is done in #323. Thanks for the PR anyway!

**Pull request closed without merging**
