### PR TITLE
Fix warnings.

### PR DESCRIPTION
**Pull request by frewsxcv**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/269)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Looks like the import is used, but should be behind `#[cfg(feature="serde")]`.

**Comment by SimonSapin** [comment]
Indeed, Travis fails:

```rust
error: no method named `description` found for type `parser::ParseError` in the current scope
    --> src/lib.rs:1523:45
     |
1523 |             serde::Error::invalid_value(err.description())
     |                                             ^^^^^^^^^^^
     |
     = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
     = help: candidate #1: `use std::error::Error;`

**Comment by frewsxcv** [comment]
Fixed.

**Pull request merged**
