### PR TITLE
Fix repository URL for AppVeyor

### PR DESCRIPTION
**Pull request by mgeisler**
For some reason, this project is not registered under `servo/rust-url` on AppVeyor.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/384)

### CODE REVIEW

**Comment by jdm** [comment]
The appveyor webhook did not like this change; appveyor returned a 404 response when it was notified about this PR.

**Comment by mgeisler** [comment]
> The appveyor webhook did not like this change; appveyor returned a 404 response when it was notified about this PR.

Oh, that's strange? I don't think the Cargo configuration has any influence on AppVeyor?

**Comment by jdm** [comment]
Oh, I totally misread the PR. That's doubly interesting.

**Comment by mgeisler** [comment]
Hehe, okay :-) I cannot see the repository settings and the failed web hook -- all I know is that the README links to https://ci.appveyor.com/project/Manishearth/rust-url and that going to https://ci.appveyor.com/project/servo/rust-url doesn't work.

**Comment by mbrubeck** [comment]
@bors-servo r+

I'm going to proceed on the assumption that the Appveyor webhook error was a weird coincidence.

**Pull request merged**
