### PR TITLE
Fix encoding::EncodingOverride when not enabling query_encoding feature

### PR DESCRIPTION
**Pull request by nox**
This is a breaking change, but at the same this fixes a bug that can cause build issues anyway, so I'm on the fence this time.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-url/431)

### CODE REVIEW

**Comment by nox** [comment]
Cc @emilio @SimonSapin @Eijebong because we all have opinions about semver.

**Comment by nox** [comment]
This may be a good opportunity to define the missing methods that don't depend on the `encoding` crate for when the feature is not enabled.

**Comment by SimonSapin** [comment]
What’s the build issue?

Note that the `encoding` module is not public and its content not re-exported. Now that `pub(crate)` is a thing, we should use it for its contents to make that more clear.

**Comment by nox** [comment]
@SimonSapin Ooooooooh. Sorry for the brainfart. 'Tis no public, so there is no problem.

**Pull request closed without merging**
